### ISSUE TITLE
./orthw: line 12: /Users/lucasgonze/.orthwconfig: No such file or directory

### ISSUE THREAD

**Issue by lucasgonze** [oss-review-toolkit/orthw#28]
1. Install orthw following recommended steps.
2. Run orthw executable
3. Get fatal error relating to configuration file

```
$ ./orthw
./orthw: line 12: /Users/lucasgonze/.orthwconfig: No such file or directory
The variable 'configuration_home' must be defined in '/Users/lucasgonze/.orthwconfig'.
```

<img width="641" alt="image" src="https://user-images.githubusercontent.com/111581/181262019-a53c71fc-de93-40fa-a7eb-c924c49f1cf8.png">

The relevant code on line 12 is:

```
orthw_config_file=~/.orthwconfig
# shellcheck source=orthconfig-template
. "$orthw_config_file"
```

Ways to improve this situation:

1. Check for the file before attempting to read it and throw an informative error message

2. Document creation of the config file before running of the executable
<img width="797" alt="image" src="https://user-images.githubusercontent.com/111581/181262926-46a200af-39f6-447b-a757-c434d1f9767b.png">

3. On failing to find configuration file, offer to auto-generate it

**Comment by tsteenbe** [comment]
@lucasgonze  We updated the README to implement above 2 "Document creation of the config file before running of the executable" - was inlcuded in a large docs improvement PR.

For "Check for the file before attempting to read it and throw an informative error message" I have some ideas for a better message but before I just fill a PR I would love to know your thoughts on it. What would you like to see?

**Comment by fviernau** [comment]
I propose https://github.com/oss-review-toolkit/orthw/pull/31 as a fix.
