### ISSUE TITLE
Add auto-curate command to generate curations and package configurations

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/orthw#34]
I propose we add to orthw an 'auto-curate' command to generate curations and package configurations. 

**Package Configuration Generation Ideas**
- Generate configurations based on existing configurations for versions already present in the configuration
- Generate configurations with path excludes for known files and/or directories used only for development (build scripts/tests) or documentation which are not included in the release artifacts. Propose we introduce a YAML file where for each package manager one can define glob expressions to exclude

**Curations Generation Ideas**
- Show warnings on the CLI if the scan results for a package contains multiple definition files so ORTHW users can know VCS path curations are likely needed. Example: Each package in the [AWS SDK for Java](https://github.com/aws/aws-sdk-java) defines https://github.com/aws/aws-sdk-java as it repository but this repo contains hundreds of pages. If say [aws-java-sdk-api-gateway](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-api-gateway) is scanned and it scan results contain multiple pom.xml file orthw should warn used on CLI with something like 'In the scan results of Maven:com.amazonaws:aws-java-sdk-api-gateway x pom.xml file were found, consider adding a VCS path curations'.

**Comment by fviernau** [comment]
Path excludes can now be generated with the following commands:

1. `orthw pc-create <package-id>
2. `orthw pc-offending`
3.  `orthw pc-create-all`

Additionally, the configuration file allows for specifying the license categories for which path excludes shall be generated.

The lions share of the work has been put into the helper-cli command in ORT in context of https://github.com/oss-review-toolkit/ort/issues/5763.

The use of that command within `orthw` has been implemented by
- https://github.com/oss-review-toolkit/orthw/pull/37
- https://github.com/oss-review-toolkit/orthw/pull/43
